ALTER TABLE user ADD COLUMN spins INTEGER DEFAULT 0;
ALTER TABLE user ADD COLUMN bungo_bux INTEGER DEFAULT 0;

CREATE TABLE spins (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL,
  winnings NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES user(id)
);